var usingNode = typeof window === 'undefined';
var constants = {};

var EVAPORATION_RATE = 0.001;
var MAX_PHEREMONE_VALUE = 1;
var MIN_PHEREMONE_VALUE = 0;

var MIN_PHEREMONE_VALUE_CHANCE = 0.01;
var ANT_ADD_PHEREMONE_AMT = 0.1;

var PHEREMONE_DISPERSE_DECAY = 0.01;

var NON_EXISTANT_SPACE = -1;

var UP_INDEX = 0;
var RIGHT_INDEX = 1;
var DOWN_INDEX = 2;
var LEFT_INDEX = 3;
var NUM_SURROUNDING_POSITIONS = 4;

if(usingNode)
{
    exports.EVAPORATION_RATE = EVAPORATION_RATE;
    exports.MAX_PHEREMONE_VALUE = MAX_PHEREMONE_VALUE;
    exports.MIN_PHEREMONE_VALUE = MIN_PHEREMONE_VALUE;
    exports.MIN_PHEREMONE_VALUE_CHANCE = MIN_PHEREMONE_VALUE_CHANCE;
    exports.ANT_ADD_PHEREMONE_AMT = ANT_ADD_PHEREMONE_AMT;
    exports.NON_EXISTANT_SPACE = NON_EXISTANT_SPACE;
    exports.UP_INDEX = UP_INDEX;
    exports.RIGHT_INDEX = RIGHT_INDEX;
    exports.DOWN_INDEX = DOWN_INDEX;
    exports.LEFT_INDEX = LEFT_INDEX;
    exports.NUM_SURROUNDING_POSITIONS = NUM_SURROUNDING_POSITIONS;
}
else
{
    constants.EVAPORATION_RATE = EVAPORATION_RATE;
    constants.MAX_PHEREMONE_VALUE = MAX_PHEREMONE_VALUE;
    constants.MIN_PHEREMONE_VALUE = MIN_PHEREMONE_VALUE;
    constants.MIN_PHEREMONE_VALUE_CHANCE = MIN_PHEREMONE_VALUE_CHANCE;
    constants.ANT_ADD_PHEREMONE_AMT = ANT_ADD_PHEREMONE_AMT;
    constants.NON_EXISTANT_SPACE = NON_EXISTANT_SPACE;
    constants.UP_INDEX = UP_INDEX;
    constants.RIGHT_INDEX = RIGHT_INDEX;
    constants.DOWN_INDEX = DOWN_INDEX;
    constants.LEFT_INDEX = LEFT_INDEX;
    constants.NUM_SURROUNDING_POSITIONS = NUM_SURROUNDING_POSITIONS;
}